name: Linux BPY builder

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
#  stable:
#    runs-on: ubuntu-latest
#    steps:
#      - name: pull repo
#        uses: actions/checkout@v1
#        
#      - name: build bpy module
#        env:
#          HUB_NAME: ${{ secrets.DOCKER_NAME }}
#          HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
#        run: |  
#          #make
#          docker login -u $HUB_NAME -p $HUB_KEY
#          docker build . -f Dockerfile -t zocker160/blender-bpy:stable
#          docker push zocker160/blender-bpy:stable
          
        
      #- name: rename
      #  run: mv ./bpy ./bpy-stable
        
      #- name: upload finished module
      #  uses: actions/upload-artifact@master
      #  with:
      #    name: Blender-bpy-stable
      #    path: ./bpy-stable
          
  master:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v1
        
      - name: build bpy module
        env:
          HUB_NAME: ${{ secrets.DOCKER_NAME }}
          HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
        run: |  
          #make
          docker login -u $HUB_NAME -p $HUB_KEY
          docker build . -f Dockerfile -t zocker160/blender-bpy:beta
          docker push zocker160/blender-bpy:beta
        
      #- name: rename
      #  run: mv ./bpy ./bpy-master
        
      #- name: upload finished module
      #  uses: actions/upload-artifact@master
      #  with:
      #    name: Blender-bpy-master
      #    path: ./bpy-master
