name: Linux BPY builder

on:
  push:
    - master
  workflow_dispatch:

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v1
        
      - name: build bpy module
        run: make
        
      - name: cleanup
        run: |
          make clean
          mv ./bpy ./bpy-stable
        
      - name: upload finished module
        uses: actions/upload-artifact@master
        with:
          name: Blender-bpy
          path: ./bpy-stable
          
  master:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v1
        
      - name: build bpy module
        run: make
        
      - name: cleanup
        run: |
          make clean
          mv ./bpy ./bpy-master
        
      - name: upload finished module
        uses: actions/upload-artifact@master
        with:
          name: Blender-bpy
          path: ./bpy-master
